version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - .:/infoarena
      - ./docker-setup/nginx.conf:/etc/nginx/nginx.conf
    links:
      - infoarena
  infoarena:
    build: .
    volumes:
      - .:/infoarena
    links:
      - memcached
      - db
  memcached:
    image: memcached
  db:
    image: mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
